import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
  orders: {
    create: (payload: any) => ipcRenderer.invoke('orders:create', payload),
    addItems: (payload: any) => ipcRenderer.invoke('orders:addItems', payload),
    updateItemQty: (payload: any) => ipcRenderer.invoke('orders:updateItemQty', payload),
    updateItemNote: (payload: any) => ipcRenderer.invoke('orders:updateItemNote', payload),
    voidItem: (payload: any) => ipcRenderer.invoke('orders:voidItem', payload),
    getOpen: () => ipcRenderer.invoke('orders:getOpen'),
    getById: (payload: any) => ipcRenderer.invoke('orders:getById', payload),
    getByTable: (payload: any) => ipcRenderer.invoke('orders:getByTable', payload),
    sendKOT: (payload: any) => ipcRenderer.invoke('orders:sendKOT', payload),
    updateStatus: (payload: any) => ipcRenderer.invoke('orders:updateStatus', payload),
    updateType: (payload: any) => ipcRenderer.invoke('orders:updateType', payload),
    applyDiscount: (payload: any) => ipcRenderer.invoke('orders:applyDiscount', payload),
    changeTable: (payload: any) => ipcRenderer.invoke('orders:changeTable', payload),
    cancelOrder: (payload: any) => ipcRenderer.invoke('orders:cancelOrder', payload),
    updateCustomer: (payload: any) => ipcRenderer.invoke('orders:updateCustomer', payload),
  },
  kds: {
    getActiveTickets: (payload?: any) => ipcRenderer.invoke('kds:getActiveTickets', payload),
    updateItemStatus: (payload: any) => ipcRenderer.invoke('kds:updateItemStatus', payload),
    updateKotStatus: (payload: any) => ipcRenderer.invoke('kds:updateKotStatus', payload),
    updateOrderStatus: (payload: any) => ipcRenderer.invoke('kds:updateOrderStatus', payload),
  },
  menu: {
    getMenus: () => ipcRenderer.invoke('menu:getMenus'),
    upsertMenu: (payload: any) => ipcRenderer.invoke('menu:upsertMenu', payload),
    duplicateMenu: (payload: any) => ipcRenderer.invoke('menu:duplicateMenu', payload),
    uploadImage: () => ipcRenderer.invoke('menu:uploadImage'),
    getAll: (menuId?: number) => ipcRenderer.invoke('menu:getAll', menuId),
    upsertItem: (payload: any) => ipcRenderer.invoke('menu:upsertItem', payload),
    deleteItem: (payload: any) => ipcRenderer.invoke('menu:deleteItem', payload),
    toggleAvailable: (payload: any) => ipcRenderer.invoke('menu:toggleAvailable', payload),
    upsertCategory: (payload: any) => ipcRenderer.invoke('menu:upsertCategory', payload),
    deleteCategory: (payload: any) => ipcRenderer.invoke('menu:deleteCategory', payload),
    getRecipe: (payload: any) => ipcRenderer.invoke('menu:getRecipe', payload),
    updateRecipe: (payload: any) => ipcRenderer.invoke('menu:updateRecipe', payload),
  },
  tables: {
    getAll: () => ipcRenderer.invoke('tables:getAll'),
    upsert: (payload: any) => ipcRenderer.invoke('tables:upsert', payload),
    delete: (payload: any) => ipcRenderer.invoke('tables:delete', payload),
    updateCustomName: (payload: any) => ipcRenderer.invoke('tables:updateCustomName', payload),
  },
  stage2: {
    categories: {
      list: (payload: any) => ipcRenderer.invoke('stage2:categories:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:categories:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:categories:deactivate', id),
    },
    menuItems: {
      list: (payload?: any) => ipcRenderer.invoke('stage2:menu-items:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:menu-items:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:menu-items:deactivate', id),
      setAvailability: (payload: any) => ipcRenderer.invoke('stage2:menu-items:set-availability', payload),
    },
    variants: {
      list: (payload: any) => ipcRenderer.invoke('stage2:variants:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:variants:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:variants:deactivate', id),
    },
    modifierGroups: {
      list: (payload?: any) => ipcRenderer.invoke('stage2:modifier-groups:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:modifier-groups:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:modifier-groups:deactivate', id),
    },
    modifiers: {
      list: (payload: any) => ipcRenderer.invoke('stage2:modifiers:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:modifiers:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:modifiers:deactivate', id),
    },
    menuItemModifierGroups: {
      list: (menuItemId: number) => ipcRenderer.invoke('stage2:menu-item-modifier-groups:list', menuItemId),
      set: (payload: any) => ipcRenderer.invoke('stage2:menu-item-modifier-groups:set', payload),
    },
    diningAreas: {
      list: (payload?: any) => ipcRenderer.invoke('stage2:dining-areas:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:dining-areas:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:dining-areas:deactivate', id),
    },
    tables: {
      list: (payload?: any) => ipcRenderer.invoke('stage2:tables:list', payload),
      save: (payload: any) => ipcRenderer.invoke('stage2:tables:save', payload),
      deactivate: (id: number) => ipcRenderer.invoke('stage2:tables:deactivate', id),
      updateStatus: (payload: any) => ipcRenderer.invoke('stage2:tables:update-status', payload),
      updateLayout: (payload: any) => ipcRenderer.invoke('stage2:tables:update-layout', payload),
    },
    audit: {
      list: (limit?: number) => ipcRenderer.invoke('stage2:audit:list', limit),
    },
  },
  payments: {
    updateStatus: (payload: any) => ipcRenderer.invoke('payments:updateStatus', payload),
    verify: (payload: any) => ipcRenderer.invoke('payments:verify', payload),
  },
  billing: {
    createBill: (payload: any) => ipcRenderer.invoke('billing:createBill', payload),
    getBill: (payload: any) => ipcRenderer.invoke('billing:getBill', payload),
  },
  print: {
    kot: (payload: any) => ipcRenderer.invoke('print:kot', payload),
    bill: (payload: any) => ipcRenderer.invoke('print:bill', payload),
  },
  inventory: {
    getAll: () => ipcRenderer.invoke('inventory:getAll'),
    getLowStock: () => ipcRenderer.invoke('inventory:getLowStock'),
    getMovements: (payload?: any) => ipcRenderer.invoke('inventory:getMovements', payload),
    convert: (payload: any) => ipcRenderer.invoke('inventory:convert', payload),
    adjust: (payload: any) => ipcRenderer.invoke('inventory:adjust', payload),
    upsertItem: (payload: any) => ipcRenderer.invoke('inventory:upsertItem', payload),
    updateRecipe: (payload: any) => ipcRenderer.invoke('inventory:updateRecipe', payload),
  },
  suppliers: {
    list: (payload?: any) => ipcRenderer.invoke('suppliers:list', payload),
    save: (payload: any) => ipcRenderer.invoke('suppliers:save', payload),
  },
  purchases: {
    list: (payload?: any) => ipcRenderer.invoke('purchases:list', payload),
    items: (payload: any) => ipcRenderer.invoke('purchases:items', payload),
    create: (payload: any) => ipcRenderer.invoke('purchases:create', payload),
    receive: (payload: any) => ipcRenderer.invoke('purchases:receive', payload),
    cancel: (payload: any) => ipcRenderer.invoke('purchases:cancel', payload),
  },
  audit: {
    list: (payload?: any) => ipcRenderer.invoke('audit:list', payload),
  },
  staff: {
    login: (payload: any) => ipcRenderer.invoke('staff:login', payload),
    logout: () => ipcRenderer.invoke('staff:logout'),
    getAll: () => ipcRenderer.invoke('staff:getAll'),
    upsert: (payload: any) => ipcRenderer.invoke('staff:upsert', payload),
    delete: (payload: any) => ipcRenderer.invoke('staff:delete', payload),
    changePin: (payload: any) => ipcRenderer.invoke('staff:changePin', payload),
  },
  shifts: {
    getActive: () => ipcRenderer.invoke('shifts:getActive'),
    open: (payload: any) => ipcRenderer.invoke('shifts:open', payload),
    close: (payload: any) => ipcRenderer.invoke('shifts:close', payload),
    getTotals: (payload: any) => ipcRenderer.invoke('shifts:getTotals', payload),
    list: (payload?: any) => ipcRenderer.invoke('shifts:list', payload),
    addCashEntry: (payload: any) => ipcRenderer.invoke('shifts:addCashEntry', payload),
    getCashEntries: (payload: any) => ipcRenderer.invoke('shifts:getCashEntries', payload),
  },
  reports: {
    daily: (payload: any) => ipcRenderer.invoke('reports:daily', payload),
    sales: (payload: any) => ipcRenderer.invoke('reports:sales', payload),
    products: (payload: any) => ipcRenderer.invoke('reports:products', payload),
    categories: (payload: any) => ipcRenderer.invoke('reports:categories', payload),
    modifiers: (payload: any) => ipcRenderer.invoke('reports:modifiers', payload),
    tables: (payload: any) => ipcRenderer.invoke('reports:tables', payload),
    kitchen: (payload: any) => ipcRenderer.invoke('reports:kitchen', payload),
    inventory: (payload?: any) => ipcRenderer.invoke('reports:inventory', payload),
    expenses: (payload: any) => ipcRenderer.invoke('reports:expenses', payload),
    gst: (payload: any) => ipcRenderer.invoke('reports:gst', payload),
    tax: () => ipcRenderer.invoke('reports:tax'),
    getPastOrders: (payload: any) => ipcRenderer.invoke('reports:getPastOrders', payload),
    printPastBill: (payload: any) => ipcRenderer.invoke('reports:printPastBill', payload),
  },
  backup: {
    export: (payload: any) => ipcRenderer.invoke('backup:export', payload),
    import: (payload: any) => ipcRenderer.invoke('backup:import', payload),
    getAutoBackupConfig: () => ipcRenderer.invoke('backup:getAutoBackupConfig'),
    setAutoBackupConfig: (payload: any) => ipcRenderer.invoke('backup:setAutoBackupConfig', payload),
    selectAutoBackupPath: () => ipcRenderer.invoke('backup:selectAutoBackupPath'),
    triggerNow: () => ipcRenderer.invoke('backup:triggerNow'),
  },
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    save: (payload: any) => ipcRenderer.invoke('settings:save', payload),
  },
  expenses: {
    getAll: (payload?: any) => ipcRenderer.invoke('expenses:getAll', payload),
    getCategories: () => ipcRenderer.invoke('expenses:getCategories'),
    create: (payload: any) => ipcRenderer.invoke('expenses:create', payload),
    delete: (payload: any) => ipcRenderer.invoke('expenses:delete', payload),
  },
  customers: {
    getAll: () => ipcRenderer.invoke('customers:getAll'),
    getById: (id: number) => ipcRenderer.invoke('customers:getById', id),
    create: (payload: any) => ipcRenderer.invoke('customers:create', payload),
    update: (payload: any) => ipcRenderer.invoke('customers:update', payload),
    delete: (payload: any) => ipcRenderer.invoke('customers:delete', payload),
    search: (payload: any) => ipcRenderer.invoke('customers:search', payload),
    settleBalance: (payload: any) => ipcRenderer.invoke('customers:settleBalance', payload),
    getHistory: (payload: any) => ipcRenderer.invoke('customers:getHistory', payload),
  },
  dashboard: {
    getMetrics: (payload: any) => ipcRenderer.invoke('dashboard:getMetrics', payload),
  },
  businessSession: {
    getActive: () => ipcRenderer.invoke('businessSession:getActive'),
    start: (payload: { staffId: number; notes?: string }) => ipcRenderer.invoke('businessSession:start', payload),
    close: (payload: { sessionId: number; staffId: number; notes?: string }) => ipcRenderer.invoke('businessSession:close', payload),
  },
  system: {
    isSetupComplete: () => ipcRenderer.invoke('system:isSetupComplete'),
    completeSetup: (payload: any) => ipcRenderer.invoke('system:completeSetup', payload),
    factoryReset: () => ipcRenderer.invoke('system:factoryReset'),
    generateRecoveryCode: () => ipcRenderer.invoke('system:generateRecoveryCode'),
    verifyRecoveryCode: (payload: any) => ipcRenderer.invoke('system:verifyRecoveryCode', payload),
    resetAdminPin: (payload: any) => ipcRenderer.invoke('system:resetAdminPin', payload),
  },
  auth: {
    check: (payload: any) => ipcRenderer.invoke('auth:check', payload),
  },
  onBackupReminder: (callback: () => void) => {
    ipcRenderer.on('backup:reminderDue', () => { callback(); });
  },
  onMenuScheduleTriggered: (callback: (data: any) => void) => {
    ipcRenderer.on('menu:scheduleTriggered', (_event, value) => { callback(value); });
  }
});
